# Generated by Django 5.0.6 on 2024-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotable',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
